package com.fui.dao.oa;

import com.fui.model.Leave;

public interface LeaveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fui_oa_leave
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fui_oa_leave
     *
     * @mbggenerated
     */
    int insert(Leave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fui_oa_leave
     *
     * @mbggenerated
     */
    int insertSelective(Leave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fui_oa_leave
     *
     * @mbggenerated
     */
    Leave selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fui_oa_leave
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Leave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fui_oa_leave
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Leave record);
}