package com.fui.dao.shiro;

import com.fui.model.Permissions;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface PermissionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fui_permissions
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fui_permissions
     *
     * @mbggenerated
     */
    int insert(Permissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fui_permissions
     *
     * @mbggenerated
     */
    int insertSelective(Permissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fui_permissions
     *
     * @mbggenerated
     */
    Permissions selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fui_permissions
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Permissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fui_permissions
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Permissions record);

    /**
     * 查询所有权限，用于给角色配置权限
     *
     * @return 所有权限信息
     */
    List<Permissions> selectAllPermission();
}