package com.fui.dao.system;

import com.fui.model.System;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface SystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fui_system
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fui_system
     *
     * @mbggenerated
     */
    int insert(System record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fui_system
     *
     * @mbggenerated
     */
    int insertSelective(System record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fui_system
     *
     * @mbggenerated
     */
    System selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fui_system
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(System record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fui_system
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(System record);

    /**
     * 查询全部数据
     *
     * @return list
     */
    List<System> selectAll();
}