package com.fui.dao.dict;

import com.fui.model.DictEntry;

import java.util.List;
import java.util.Map;

public interface DictEntryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fui_dict_entry
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fui_dict_entry
     *
     * @mbggenerated
     */
    int insert(DictEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fui_dict_entry
     *
     * @mbggenerated
     */
    int insertSelective(DictEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fui_dict_entry
     *
     * @mbggenerated
     */
    DictEntry selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fui_dict_entry
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DictEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fui_dict_entry
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DictEntry record);

    List<DictEntry> query(Map<String, Object> param);
}